### ISSUE TITLE
MinGW lzz errors

### ISSUE THREAD

**Issue by xKamuna** [mjspncr/basilcc#11]
There are a few errors in the .lzz files when building on mingw-w64, I'm not sure if they're the same with the normal mingw:
Add
```c++
#include <sys/types.h>
```
to all #hdr...#end directives (make one if it doesn't exist) in files where size_t is used.

There are also some issues I had with the make.include in the maketools directory and building, but those just have to do with path inconsistencies, being on Windows/MSYS2 instead of Linux while building,  Here are the things I changed for reference:

Remove the first variable from BUILDDIR (DEVDIR) and change it to an absolute Windows path (or set up a new variable for it).

Add missing libraries and includes to the default library/include path.

**Comment by mjspncr** [comment]
Added include for size_t (#12) thanks.
